apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: neo4jcluster
servers: 1
agents: 4
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"
options:
  k3d:
    wait: true
    timeout: "300s"
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
