neo4j:
  name: "neo4jcluster"
  minimumClusterSize: 3
  resources:
    cpu: "1"
    memory: "4Gi"
  password: "password123"
  edition: "enterprise"
  acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: "defaultStorageClass"